# Generated by Django 3.1.2 on 2021-06-10 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210609_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateField(),
        ),
    ]
