# Generated by Django 3.1.7 on 2021-06-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210610_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
